[book]
authors = ["Fuel Labs <contact@fuel.sh>"]
language = "en"
multilingual = false
src = "src"
title = "The Fuel Book"

[output.html]
git-repository-url = "https://github.com/FuelLabs/fuel-docs"

[rust]
edition = "2021"

[output.html.redirect]
"/developer-quickstart.html" = "https://fuelbook.fuel.network/master/quickstart/developer-quickstart.html"