[book]
authors = ["Fuel Labs <contact@fuel.sh>"]
language = "en"
multilingual = false
src = "src"
title = "The Fuel Book"
google_analytics_id: "G-SB795MHP73"

[output.html]
git-repository-url = "https://github.com/FuelLabs/fuel-docs"

[rust]
edition = "2021"
